"""add password reset sessions and auth rate limits

Revision ID: 210a3fe9aa42
Revises: 7d929a71a53d
Create Date: 2026-08-21 01:47:49.111603

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '210a3fe9aa42'
down_revision: str | None = '7d929a71a53d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=320), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_rate_limits')),
    sa.UniqueConstraint('scope', 'key', name='uq_auth_rate_limits_scope_key')
    )
    op.create_table('password_reset_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_sessions'))
    )
    op.create_index('ix_password_reset_sessions_expires_at', 'password_reset_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_sessions_token_hash'), 'password_reset_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_sessions_user_id'), 'password_reset_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_sessions_user_id'), table_name='password_reset_sessions')
    op.drop_index(op.f('ix_password_reset_sessions_token_hash'), table_name='password_reset_sessions')
    op.drop_index('ix_password_reset_sessions_expires_at', table_name='password_reset_sessions')
    op.drop_table('password_reset_sessions')
    op.drop_table('auth_rate_limits')
    # ### end Alembic commands ###
