"""add transactions categories ingestions merchant overrides

Revision ID: b05017440e98
Revises: 210a3fe9aa42
Create Date: 2026-08-21 18:03:26.863480

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.seeds.categories import DEFAULT_CATEGORIES

revision: str = 'b05017440e98'
down_revision: str | None = '210a3fe9aa42'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('expense', 'income', 'other', name='category_type', native_enum=False, length=16), nullable=False),
    sa.Column('icon', sa.String(length=64), server_default=sa.text("'label'"), nullable=False),
    sa.Column('color', sa.String(length=7), server_default=sa.text("'#757575'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('1000'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('expense', 'income', 'other')", name=op.f('ck_categories_category_type')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_index('uq_categories_global_slug', 'categories', ['slug'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('uq_categories_user_slug', 'categories', ['user_id', 'slug'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('merchant_category_overrides',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_key', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_merchant_category_overrides_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_category_overrides')),
    sa.UniqueConstraint('user_id', 'merchant_key', name='uq_merchant_overrides_user_key')
    )
    op.create_index(op.f('ix_merchant_category_overrides_user_id'), 'merchant_category_overrides', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'PKR'"), nullable=False),
    sa.Column('type', sa.Enum('debit', 'credit', name='transaction_type', native_enum=False, length=16), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=False),
    sa.Column('merchant_details', sa.String(length=500), nullable=True),
    sa.Column('merchant_normalized', sa.String(length=200), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recurring_group_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=100), server_default=sa.text("'Uncategorized'"), nullable=False),
    sa.Column('category_source', sa.String(length=64), server_default=sa.text("'rule'"), nullable=False),
    sa.Column('payment_method', sa.String(length=64), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('bank', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('account_id', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('account_id_masked', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('transaction_time', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('day', sa.String(length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('external_id_type', sa.Enum('tid', 'ref', 'stan', 'unknown', name='external_id_type', native_enum=False, length=16), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('dedup_key', sa.String(length=256), nullable=False),
    sa.Column('sms_source', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('parse_confidence', sa.Numeric(precision=4, scale=3), server_default=sa.text('1'), nullable=False),
    sa.Column('is_auto_detected', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Enum('active', 'deleted', 'needs_review', name='transaction_status', native_enum=False, length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("external_id_type IN ('tid', 'ref', 'stan', 'unknown')", name=op.f('ck_transactions_external_id_type')),
    sa.CheckConstraint("status IN ('active', 'deleted', 'needs_review')", name=op.f('ck_transactions_transaction_status')),
    sa.CheckConstraint("type IN ('debit', 'credit')", name=op.f('ck_transactions_transaction_type')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_transactions_amount_non_negative')),
    sa.CheckConstraint('parse_confidence >= 0 AND parse_confidence <= 1', name=op.f('ck_transactions_parse_confidence_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('user_id', 'dedup_key', name='uq_transactions_user_dedup')
    )
    op.create_index('ix_transactions_user_amount_date', 'transactions', ['user_id', 'amount', 'transaction_date', 'id'], unique=False)
    op.create_index('ix_transactions_user_date_id', 'transactions', ['user_id', 'transaction_date', 'id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_user_merchant_date', 'transactions', ['user_id', 'merchant_normalized', 'transaction_date'], unique=False)
    op.create_index('ix_transactions_user_status_date', 'transactions', ['user_id', 'status', 'transaction_date'], unique=False)
    op.create_table('raw_ingestions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw', sa.String(length=8000), nullable=False),
    sa.Column('source', sa.Enum('ios_shortcut', 'gmail', 'manual', name='ingestion_source', native_enum=False, length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_id', sa.String(length=256), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('received', 'parsed', 'duplicate', 'needs_parse', 'failed', name='ingestion_status', native_enum=False, length=32), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('ios_shortcut', 'gmail', 'manual')", name=op.f('ck_raw_ingestions_ingestion_source')),
    sa.CheckConstraint("status IN ('received', 'parsed', 'duplicate', 'needs_parse', 'failed')", name=op.f('ck_raw_ingestions_ingestion_status')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_raw_ingestions_transaction_id_transactions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_raw_ingestions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_ingestions'))
    )
    op.create_index(op.f('ix_raw_ingestions_user_id'), 'raw_ingestions', ['user_id'], unique=False)
    op.create_index('ix_raw_ingestions_user_status_received', 'raw_ingestions', ['user_id', 'status', 'received_at'], unique=False)

    categories = sa.table(
        "categories",
        sa.column("slug", sa.String),
        sa.column("name", sa.String),
        sa.column("type", sa.String),
        sa.column("icon", sa.String),
        sa.column("color", sa.String),
        sa.column("sort_order", sa.Integer),
        sa.column("is_default", sa.Boolean),
    )
    op.bulk_insert(
        categories,
        [
            {
                "slug": item["slug"],
                "name": item["name"],
                "type": item["type"].value,
                "icon": item["icon"],
                "color": item["color"],
                "sort_order": item["sort_order"],
                "is_default": True,
            }
            for item in DEFAULT_CATEGORIES
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_ingestions_user_status_received', table_name='raw_ingestions')
    op.drop_index(op.f('ix_raw_ingestions_user_id'), table_name='raw_ingestions')
    op.drop_table('raw_ingestions')
    op.drop_index('ix_transactions_user_status_date', table_name='transactions')
    op.drop_index('ix_transactions_user_merchant_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index('ix_transactions_user_date_id', table_name='transactions')
    op.drop_index('ix_transactions_user_amount_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_merchant_category_overrides_user_id'), table_name='merchant_category_overrides')
    op.drop_table('merchant_category_overrides')
    op.drop_index('uq_categories_user_slug', table_name='categories', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_categories_global_slug', table_name='categories', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
